### ISSUE TITLE
Video not attaching when trying to call participant twice

### ISSUE THREAD

**Issue by bmctigue** [twilio/video-quickstart-swift#7]
When I make the first call to the participant, the video on both ends work fine. However, I hang up the call and try to call the same person again. The participants sees the new invitation, but the remote video is never attached. Here is the sequence the participant is logging:

Connected as john
didReceiveInvite from: bruce
added media track
video dimensions changed

// video is working on the first invitation
didConnectParticipant: bruce
participant attached remote view
WARNING: no real random source present!

// video is not working after hangup and inviting again, remote view is not attached.
didDisconnectParticipant
conversationEnded
didReceiveInvite from: bruce
didConnectParticipant: bruce
WARNING: no real random source present!

**Comment by jhk115** [comment]
@bmctigue were able to solve this issue?

**Comment by bmctigue** [comment]
There were quite a few updates since I opened this, but I haven't had a chance to test it locally. I think we can go ahead and close this. Rep says this bug is fixed.

**Comment by SunilRumbaLama** [comment]
this issue still persists. The local media and the remote media is not attached on the second call.

**Comment by ptankTwilio** [comment]
Hi @SunilRumbaLama ,

What version of Video SDK are you using? Can you elaborate more on the scenario please?

-Piyush

**Comment by SunilRumbaLama** [comment]
I am using   ```
 <script src="https://media.twiliocdn.com/sdk/js/common/v0.1/twilio-common.min.js"></script>
  <script src="https://media.twiliocdn.com/sdk/js/conversations/v0.13/twilio-conversations.min.js"></script>
```
I call perform the video call successfully for the first time. However, when i disconnect the conversation and try the call again the second time. My local and remote media are not attached on the calling end. Furthermore, i keep getting the invitation even after i disconnect the conversation. Does disconnecting conversation not reinitiate the conversation.
